# Generated by Django 5.2.8 on 2025-12-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_data_registro_alter_produto_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
