# Generated by Django 5.1 on 2025-12-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_produto_data_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='un_medida',
            field=models.CharField(default='unidade', max_length=20),
        ),
    ]
