# Generated by Django 5.1 on 2025-12-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_data_vencimento_produto_un_medida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='data_vencimento',
            new_name='vencimento',
        ),
    ]
